### ISSUE TITLE
The client crashes When a thaumcraft server switching to another thaumcraft server  with bungeecord.

### ISSUE THREAD

**Issue by ccxufo** [densitycraft/ForgePacketFix#4]
I am sorry for my broken English.
when a player Hold a wang(installed foucus) switch to another server,the client would crash.
it only happen when thaumcraft server switch to thaumcraft,but vanilla switch to thaumcraft is not be. 
All is okay when I switch to server without BungeeCord. I'm in doubt is caused by thaumcraft.
All is okay when I only install thaumcraft mod in server,but I add others mod in to server , client would go crash. 
The same problem I also  submitted to HexagonMC.
 

> ---- Minecraft Crash Report ----
// You're mean.
Time: 16-10-7 下午1:13
Description: Unexpected error

java.lang.ClassCastException: zeldaswordskills.item.ItemBomb cannot be cast to thaumcraft.api.wands.ItemFocusBasic
at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28 
 
> 
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 16-10-6 下午3:26
Description: Rendering item

java.lang.ClassCastException: com.teammetallurgy.metallurgy.tools.Hoe cannot be cast to thaumcraft.api.wands.ItemFocusBasic
at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1328)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 
 

> ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 16-10-7 上午8:38
Description: Unexpected error

java.lang.ClassCastException: noppes.npcs.items.ItemNpcArmor cannot be cast to thaumcraft.api.wands.ItemFocusBasic
	at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
	at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
	at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by thomas15v** [comment]
This error is a clientside thaumcraft error and can be resolved by sending a clear inventory packet to the server. However bungeecord doesn't do that, and I also haven't spend my time trying to send such packets.

Also This project is depricated.
